server:
  port: 8080

naver:
  client-id: d0rEPpWd8iw0pnMQurZM
  client-secret: ke8hlrD2jL

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
